- name: Configure Docker on EC2 Instances
  hosts: project
  become: true
  connection: ssh
  tasks:
    - name: Updating apt
      command: sudo apt-get update
      
    - name: Install Docker
      command: sudo apt-get install -y docker.io
      become: yes

    - name: Start Docker Service
      command: sudo systemctl start docker
      become: yes

    - name : stop existing containers
      shell: docker stop $(docker ps -a -q)
      
    - name : delete all containers
      shell: docker rm $(docker ps -a -q)

    - name: Start Docker Service
      command: docker run -d -p 8084:8081 s009/insurance:1.0
      become: yes
