trigger:
- main

pool:
  name: 'default'  # Use the default agent pool

steps:
- script: |
    # Set JAVA_HOME to point to OpenJDK 11
    export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    echo "JAVA_HOME is set to $JAVA_HOME"
  displayName: 'Set JAVA_HOME'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
