trigger:
- main

stages:
- stage: Build
  displayName: Build Maven Project
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'
      
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '/home/vsts/work/1/s/target'
        artifact: 'sourabh'
        publishLocation: 'pipeline'

        

- stage: BuildDockerImage
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPushDockerImage
    pool:
      vmImage: ubuntu-latest
    steps:
    # Step 1: Download the pipeline artifact
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'sourabh'
        path: $(Build.ArtifactStagingDirectory)

    - script: |
        ls 
        pwd
        cd /home/vsts/work/1/a
        ls
        jar_location=$(find $(pwd) -name "*.jar" -type f)
        echo "Location of *.jar file: $jar_location"
      displayName: 'List Target Directory Contents'

    # Step 2: Build and push Docker image