trigger:
- main

pool:
  name: 'default'  # Use the default agent pool

jobs:
- job: Build
  steps:
  - script: |
      # Install OpenJDK 11
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk

      # Install Apache Maven
      sudo apt-get install -y maven
    displayName: 'Install Java and Maven'

  - script: 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
    displayName: 'Set JAVA_HOME'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      goals: 'package'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
