# Define trigger for the pipeline
trigger:
- main

# Define stages for the pipeline
stages:
- stage: Build
  displayName: 'Build Maven Project'
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # Step 1: Execute Maven build
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'

    # Step 2: Publish JAR artifact
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/target/*.jar'
        artifact: 'drop'

- stage: BuildDockerImage
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPushDockerImage
    pool:
      vmImage: ubuntu-latest
    steps:
    # Step 1: Download the pipeline artifact
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'drop'
        path: $(Build.ArtifactStagingDirectory)

    # Step 2: Build and push Docker image
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 's009/azureinsurenceproject'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.ArtifactStagingDirectory)'
