trigger:
- main

pool:
  name: 'default'  # Use the default agent pool

jobs:
- job: Build
  steps:
  - script: |
      echo "##[set-env name=JAVA_HOME;]path_to_your_jdk"  # Replace path_to_your_jdk with the actual JDK path
    displayName: 'Set JAVA_HOME'

  - script: |
      echo "##[set-env name=JAVA_HOME_11_X64;]$(JAVA_HOME)"
    displayName: 'Set JAVA_HOME_11_X64'

  - script: 'echo "##vso[task.setvariable variable=JAVA_HOME;]$(JAVA_HOME)"'
    displayName: 'Set JAVA_HOME Variable'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      goals: 'package'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
