trigger:
- main

stages:
- stage: Build
  displayName: Build Maven Project
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'

    # Step 2: Publish JAR artifact
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$/home/vsts/work/1/s/target/*.jar'
        artifact: 'drop'

        

- stage: BuildDockerImage
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPushDockerImage
    pool:
      vmImage: ubuntu-latest
    steps:
    # Step 1: Download the pipeline artifact
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'drop'
        path: $(Build.ArtifactStagingDirectory)

    # Step 2: Build and push Docker image
    - task: Docker@2
      inputs:
        containerRegistry: 'Dockerhub'
        repository: 's009/azureinsurenceproject'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '$(Build.ArtifactStagingDirectory)'
